name: "docker-push-aws"
description: Create image based on .Dockerfile and push to AWS
inputs:
  container-name:
    description: The name for the docker container
    required: false
    default: ${{ github.event.repository.name }}
  software-version:
    description: The version of the software
    required: false
    default: latest
  aws-access-key-id:
    description: Access key ID for AWS
    required: true
  aws-secret-access-key:
    description: Secret access key for AWS
    required: true
  aws-region:
    description: Secret access key for AWS
    required: false
    default: eu-west-1
  function-name:
    description: Function name on AWS
    required: true
  additional-path:
    description: Additional path in case the root directory does not contain the Dockerfile (ex. /grafana/Dockerfile)
    required: false
    default: ""
  dotnet-version:
    description: Specify which .NET version to use
    required: false
    default: "9.x"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{inputs.dotnet-version}}
    - name: Build Docker Image
      shell: bash
      run: docker build -t ${{inputs.container-name}}:${{inputs.software-version}} workflow/repository/${{inputs.additional-path}}
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ inputs.aws-access-key-id }}
        secret-access-key: ${{ inputs.aws-secret-access-key }}
        region: ${{inputs.aws-region}}
        local-image: ${{inputs.container-name}}:${{inputs.software-version}}
        image: ${{inputs.container-name}}:${{inputs.software-version}}